version: '2'

services:
  mongo:
    image: mongo
  cornauth:
    image: cornauth
    ports:
      - "33000:80"
    build:
      context: ./CornAuth
      dockerfile: Dockerfile
    depends_on:
      - mongo